### ISSUE TITLE
New error on the newest version when a server saves automatically

### ISSUE THREAD

**Issue by Daniil1288** [RestoreMonarchyPlugins/MoreHomes#2]
```
[01.11.2019 21:40:33] [Info] Saving server
[01.11.2019 21:40:33] [Error] Object reference not set to an instance of an object
[01.11.2019 21:40:33] [Error]   at RestoreMonarchy.MoreHomes.Utilities.PlayerDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x00032] in <0424c806cf0b4a3189d3606683d21965>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00001] in <0424c806cf0b4a3189d3606683d21965>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <0424c806cf0b4a3189d3606683d21965>:0 
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <239af456bebd4a8a95e495f78ebd9f92>:0 
```

**Comment by RestoreMonarchy** [comment]
When did it begin to happend?

**Comment by Daniil1288** [comment]
Sorry for the late reply,
The default config was not edited.
Yeah, the plugin still works. Strangely enough it doesn't happen when I manually save. 
I can compile and test the newest version if you think it's fixed now (if you want me to).

**Comment by RestoreMonarchy** [comment]
Yes please try to use the newer version
~thanks

**Comment by Daniil1288** [comment]
Still have this error and players are reporting that they can't tp to a bed:
```
[02.11.2019 21:06:22] [Info] Saving server
[02.11.2019 21:06:22] [Error] Object reference not set to an instance of an object
[02.11.2019 21:06:22] [Error]   at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x00002] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00001] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <2260506d5d6449009954337ca0e9ad80>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <239af456bebd4a8a95e495f78ebd9f92>:0 
[02.11.2019 21:06:24] [Info] [Group] [Player] ViperRP[^_^)(^_^ ViperRP]: "/home"
[02.11.2019 21:06:24] [Error] An error occured while executing home []: System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0000d] in <fbb5ed17eb6e46c680000f8910ebb50c>:0 
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <fbb5ed17eb6e46c680000f8910ebb50c>:0 
  at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.GetPlayer (System.Collections.Generic.List`1[T] data, System.UInt64 playerId) [0x0000e] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.GetPlayerBed (System.Collections.Generic.List`1[T] data, System.UInt64 playerId, System.String name) [0x0000e] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.Commands.HomeCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00049] in <2260506d5d6449009954337ca0e9ad80>:0 
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <466fa14d466749559a64a11ae8acbc60>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x001b2] in <466fa14d466749559a64a11ae8acbc60>:0 
```

**Comment by Daniil1288** [comment]
Actually, could be caused by this plugin conflicting with WreckingBall (automatically cleans buildables):
```
[03.11.2019 12:42:55] [Info] WreckingBall >> Getting list of player buildables to cleanup.
[03.11.2019 12:42:56] [Info] WreckingBall >> Found 7 records, processing 7 records.
[03.11.2019 12:42:56] [Info] WreckingBall >> No elements found for player: [Player] Cyber [Cyber234] (76561198969577384).
[03.11.2019 12:42:56] [Info] WreckingBall >> Getting list of player files to cleanup.
[03.11.2019 12:42:56] [Info] WreckingBall >> No records found.
[03.11.2019 12:42:56] [Info] WreckingBall >> No elements found for player: [Player] shadow [Shadow12] (76561198983634925).
[03.11.2019 12:42:56] [Info] WreckingBall >> No elements found for player: [Player] MAR6MEL0U [MAR6MEL0Uu] (76561198931492624).
[03.11.2019 12:42:56] [Info] WreckingBall >> No elements found for player: [Player] BAN [☢¯\_(ツ)_/¯☢] (76561198136808094).
[03.11.2019 12:42:56] [Info] WreckingBall >> No elements found for player: [Player] Joker [Joker╰_╯] (76561198448044595).
[03.11.2019 12:42:56] [Info] WreckingBall >> No elements found for player: [Player] Daniyar200627 [daniyar200627] (76561198986392443).
[03.11.2019 12:42:56] [Info] WreckingBall >> No elements found for player: [Player] Momonga [Ainz Ooal Gown | Momonga] (76561198123663313).
[03.11.2019 12:42:56] [Info] WreckingBall >> Finished with cleaning up the player elements in this run.
[03.11.2019 12:43:17] [Error] Collection was modified; enumeration operation may not execute.
[03.11.2019 12:43:17] [Error]   at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x000a2] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00001] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <2260506d5d6449009954337ca0e9ad80>:0 
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <239af456bebd4a8a95e495f78ebd9f92>:0 
```

**Comment by RestoreMonarchy** [comment]
I'm not sure, because it works on my servers, but I don't use WreckingBall.
Maybe it's because of the decay destroying the beds?

**Comment by Daniil1288** [comment]
And some people also report occasionally tping to homes that aren't theirs but to random ones instead.

**Comment by RestoreMonarchy** [comment]
I'll try to fix it later today or tomorrow, because I don't have time. I'll have a closer look on Friday.

**Comment by Daniil1288** [comment]
Removed WreckingBall for now, still having this error pop up in the logs:
[09.11.2019 11:52:29] [Info] Saving server
[09.11.2019 11:54:19] [Error] Object reference not set to an instance of an object
[09.11.2019 11:54:19] [Error]   at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x00002] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00001] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <2260506d5d6449009954337ca0e9ad80>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <239af456bebd4a8a95e495f78ebd9f92>:0

**Comment by Daniil1288** [comment]
What's more, I just tried rebooting the server and doing /save in the console and the first one errored out, the second time I tried it didn't:
```
[09.11.2019 15:09:41] [Info] MoreHomes >> Loading Players data...
[09.11.2019 15:09:41] [Info] MoreHomes >> Successfully loaded 18 Players!
[09.11.2019 15:09:41] [Error] Collection was modified; enumeration operation may not execute.
[09.11.2019 15:09:41] [Error]   at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x000a2] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00001] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <2260506d5d6449009954337ca0e9ad80>:0 
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <b4383d5e0f9049f699a7bb7b6b7eed43>:0 
[09.11.2019 15:09:41] [Info] Successfully saved the game.
[09.11.2019 15:09:49] [Info] Successfully saved the game.
```

**Comment by Daniil1288** [comment]
And also if you unload the plugin and do /save it fails anyway:
```
[09.11.2019 18:56:52] [Error] Object reference not set to an instance of an object
[09.11.2019 18:56:52] [Error]   at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x00002] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00001] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <2260506d5d6449009954337ca0e9ad80>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <b4383d5e0f9049f699a7bb7b6b7eed43>:0 
[09.11.2019 18:56:52] [Info] Successfully saved the game.
[09.11.2019 18:56:53] [Error] Object reference not set to an instance of an object
[09.11.2019 18:56:53] [Error]   at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x00002] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00001] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <2260506d5d6449009954337ca0e9ad80>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <b4383d5e0f9049f699a7bb7b6b7eed43>:0 
[09.11.2019 18:56:53] [Info] Successfully saved the game.
[09.11.2019 18:56:59] [Info] Unloading MoreHomes
[09.11.2019 18:57:01] [Info] 
[unloading] MoreHomes
[09.11.2019 18:57:01] [Info] MoreHomes >> MoreHomes has been unloaded!
[09.11.2019 18:57:01] [Error] Object reference not set to an instance of an object
[09.11.2019 18:57:01] [Error]   at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x00002] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00001] in <2260506d5d6449009954337ca0e9ad80>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <2260506d5d6449009954337ca0e9ad80>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <b4383d5e0f9049f699a7bb7b6b7eed43>:0 
[09.11.2019 18:57:01] [Info] Successfully saved the game.
```

**Comment by RestoreMonarchy** [comment]
I'm gonna fix it later today, but don't worry about the error it saves your map anyways.

**Comment by RestoreMonarchy** [comment]
The issue should be solved and /destroyhome and /restorehomes command should be fixed too in version **1.2.0.1** or build #25 on Rocket Harbor

**Comment by Daniil1288** [comment]
![image](https://user-images.githubusercontent.com/1404955/68550261-5b8b4e00-0412-11ea-86e7-98c2f7a721b1.png)
hmm, not quite just yet.

**Comment by RestoreMonarchy** [comment]
I don't recommend you using rocket reload, because most plugins don't support it :/

**Comment by Daniil1288** [comment]
Oh, wiping the json data config and doing /restorehomes helped with the error, it's gone now. Weird.
Thing is, players have been reporting strange things happening after doing /home on the previous version (1.2.0.0) with this error present (or rather being spammed every time the server saves) in console. Here's a couple of screenshots I had received from them (they would get stuck in textures, couldn't place buildables, etc.; moreover, relogging wouldn't even help):
1. Without the error, this player was building a tower.
![image](https://user-images.githubusercontent.com/1404955/68550464-03554b80-0414-11ea-9fe0-13042390343a.png)
2. After the error appeared.
![image](https://user-images.githubusercontent.com/1404955/68550470-10723a80-0414-11ea-86ae-52c746f1394e.png)
![image](https://user-images.githubusercontent.com/1404955/68550476-19630c00-0414-11ea-8234-2779a0fe601c.png)
I've also had a couple of videos on my server but most of them were recorded by players using their phones for some reason and I simply can't find the single good one that I wanted to link so whatever.
Could be some other plugin screwing up, too, I'll keep the latest version of MoreHomes installed on my server for a day or so and report if any error occurs again or if players start reporting anything again.

**Comment by RestoreMonarchy** [comment]
That's pretty weird about this tower. Do you mean that doorway and window frames were gone?
Also about being teleported somewhere else than supposed, I believe the issue should be fixed in 1.2.0.1, however keep me tuned if the error appears again. Thank you for reporting all the bugs and helping me keep plugin updated.

Greetings

**Comment by Daniil1288** [comment]
![image](https://user-images.githubusercontent.com/1404955/69161488-4c845a00-0afc-11ea-9ceb-cb4b22a96bab.png)
people are still unable to claim their beds/set home time from time,
having to do /restorehomes which restores some homes manually

**Comment by Daniil1288** [comment]
Manually saving still fails time from time:
```
[loading] MoreHomes
[24.11.2019 21:50:51] [Info] [registered] /home (RestoreMonarchy.MoreHomes.Commands.HomeCommand/home)
[24.11.2019 21:50:51] [Info] [registered] /homes (RestoreMonarchy.MoreHomes.Commands.HomesCommand/homes)
[24.11.2019 21:50:51] [Info] [registered] /destroyhome (RestoreMonarchy.MoreHomes.Commands.DestroyHomeCommand/destroyhome)
[24.11.2019 21:50:51] [Info] [registered] /renamehome (RestoreMonarchy.MoreHomes.Commands.RenameHomeCommand/renamehome)
[24.11.2019 21:50:51] [Info] [registered] /restorehomes (RestoreMonarchy.MoreHomes.Commands.RestoreHomesCommand/restorehomes)
[24.11.2019 21:50:51] [Info] MoreHomes >> MoreHomes 1.2.0.1 has been loaded!
[24.11.2019 21:50:51] [Info] MoreHomes >> Brought to you by RestoreMonarchy.com
[24.11.2019 21:50:51] [Error] Collection was modified; enumeration operation may not execute.
[24.11.2019 21:50:51] [Error]   at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x0006d] in <bfe5f2adf5aa4162acf0cffd55e0b13e>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00000] in <bfe5f2adf5aa4162acf0cffd55e0b13e>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <bfe5f2adf5aa4162acf0cffd55e0b13e>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <b4383d5e0f9049f699a7bb7b6b7eed43>:0 
[24.11.2019 21:50:51] [Info] Successfully saved the game.
[24.11.2019 21:50:54] [Info] Successfully restored 4 homes!
[24.11.2019 21:50:54] [Error] Collection was modified; enumeration operation may not execute.
[24.11.2019 21:50:54] [Error]   at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x0000b] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x0006d] in <bfe5f2adf5aa4162acf0cffd55e0b13e>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00000] in <bfe5f2adf5aa4162acf0cffd55e0b13e>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <bfe5f2adf5aa4162acf0cffd55e0b13e>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <b4383d5e0f9049f699a7bb7b6b7eed43>:0 
[24.11.2019 21:50:54] [Info] Successfully saved the game.

```

**Comment by RestoreMonarchy** [comment]
Let's hope version 1.2.0.2 *build#29* will permanently solve it. Also added, so /destroyhome should in future solve all individual players issues with having their bed not exists, but it will be still removed with /destroyhome command.

**Comment by Daniil1288** [comment]
Just got around to installing the update and immediately after installation I tried out the /restorehomes command:
```
[06.12.2019 10:21:47] [Error] An error occured while executing restorehomes []: System.NullReferenceException: Object reference not set to an instance of an object
  at RestoreMonarchy.MoreHomes.Commands.RestoreHomesCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x000ab] in <866b081215954d21997e3c00a39cdc7c>:0 
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <466fa14d466749559a64a11ae8acbc60>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x001b2] in <466fa14d466749559a64a11ae8acbc60>:0 
[06.12.2019 10:21:51] [Error] An error occured while executing restorehomes []: System.NullReferenceException: Object reference not set to an instance of an object
  at RestoreMonarchy.MoreHomes.Commands.RestoreHomesCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x000ab] in <866b081215954d21997e3c00a39cdc7c>:0 
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <466fa14d466749559a64a11ae8acbc60>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x001b2] in <466fa14d466749559a64a11ae8acbc60>:0 
[06.12.2019 10:21:52] [Error] Value cannot be null.
Parameter name: obj
[06.12.2019 10:21:52] [Error]   at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_monitor_enter_v4_internal(object,intptr)
  at RestoreMonarchy.MoreHomes.Utilities.PlayersDataUtility.UpdateBeds (System.Collections.Generic.List`1[T] data) [0x00005] in <866b081215954d21997e3c00a39cdc7c>:0 
  at RestoreMonarchy.MoreHomes.Utilities.DataStorageUtility.SavePlayersData (RestoreMonarchy.MoreHomes.Utilities.DataStorage storage, System.Collections.Generic.List`1[T] data) [0x00001] in <866b081215954d21997e3c00a39cdc7c>:0 
  at RestoreMonarchy.MoreHomes.MoreHomesPlugin.<Load>b__22_1 () [0x0000c] in <866b081215954d21997e3c00a39cdc7c>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void()
  at SDG.Unturned.SaveManager.broadcastPostSave () [0x00007] in <b4383d5e0f9049f699a7bb7b6b7eed43>:0 
[06.12.2019 10:21:52] [Info] Successfully saved the game.
[06.12.2019 10:21:54] [Error] An error occured while executing restorehomes []: System.NullReferenceException: Object reference not set to an instance of an object
  at RestoreMonarchy.MoreHomes.Commands.RestoreHomesCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x000ab] in <866b081215954d21997e3c00a39cdc7c>:0 
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <466fa14d466749559a64a11ae8acbc60>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x001b2] in <466fa14d466749559a64a11ae8acbc60>:0 

```
Should I be wiping the server & MoreHomesData.json?

**Comment by Daniil1288** [comment]
Suspecting it might be related to me doing a /rocket reload first.

**Comment by RestoreMonarchy** [comment]
@Daniil1288 so was it caused just by rocket reload?

**Comment by Daniil1288** [comment]
@RestoreMonarchy, yeah but the problem with being unable to do /rocket reload is: say, I need to change the config of your MoreHomes plugin (change permissions etc.) but I can't apply changes without restarting the whole server because unlike other plugins /rocket reload morehomes breaks it.

**Comment by papershredder432** [comment]
> @RestoreMonarchy, yeah but the problem with being unable to do /rocket reload is: say, I need to change the config of your MoreHomes plugin (change permissions etc.) but I can't apply changes without restarting the whole server because unlike other plugins /rocket reload morehomes breaks it.

Reloading Rocket is a bad idea. It breaks most plugins when you do it. Just restart your server.

**Comment by Daniil1288** [comment]
@papershredder432, in fact MoreHomes is the only plugin that breaks on my server after a /rocket reload. How am I supposed to change the configuration of the plugin without restarting my server, then?
Also players are reporting that /home doesn't work even after doing /restorehomes (which for some reason says 'successfully restored 3 homes' even though the server wasn't shutdown without saving previously), and the bedrolls are unclaimable for them, here's a video:
[Bandicam 2019-12-15 17-22-12-604-1.zip](https://github.com/RestoreMonarchyPlugins/MoreHomes/files/3965025/Bandicam.2019-12-15.17-22-12-604-1.zip)
No /rocket reload was done this time around (the console's void of errors.)

**Comment by RestoreMonarchy** [comment]
* It probably says that 0 beds were restarted because `restorehomes` only looks and try to find a beds that are not in database yet, but exist on the map.
* Can you send me your rocket log when you try to claim a bed and it doesn't work? I believe it should probably throw an error if, so you can send me it here too, but also give me a full log please.
* btw zipping videos doesn't give you much, mp4 are already strongly compressed 😁 
Thanks

**Comment by Daniil1288** [comment]
@RestoreMonarchy, yeah, github just doesn't support the upload of mp4 files. Had to zip it.
Here's the log, happened at 17-22-12, 15-12-19 (yesterday)
[Rocket.1576475324.log](https://github.com/RestoreMonarchyPlugins/MoreHomes/files/3968494/Rocket.1576475324.log)

**Comment by Daniil1288** [comment]
And /rocket reload also makes doors disappear yet players can't walk through them: 
[index-f3-v1-a1-index-f3-v1-a1.zip](https://github.com/RestoreMonarchyPlugins/MoreHomes/files/3991855/index-f3-v1-a1-index-f3-v1-a1.zip) - video sent by a player (who doesn't know how to record a screen properly...)
[Rocket.1576648210.log](https://github.com/RestoreMonarchyPlugins/MoreHomes/files/3991856/Rocket.1576648210.log) - log.
